version: "3"
services:
  # 如果需要多账号并发请求，可以新建一行asm_unicom 然后拷贝asm_unicom下面的代码，并修改container_name,hostname方便管理
  asm_unicom:
    image: xclamp/asm-wrapper:bilibili
    container_name: asm_bilibili
    restart: always
    tty: true
    network_mode: "bridge"
    hostname: asm_bilibili
    volumes:
      - ./:/AutoSignMachine/config #同步脚本地址
    environment:
      - enable_bilibili=true #签到开关 false / true
      - DedeUserID=41*****1073 # DedeUserID
      - SESSDATA=b6*********4a581 #SESSDATA
      - bili_jct=05*********333*b1 #bili_jct
